name: Compilar Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar tarefa
        uses: actions/checkout@v4

      - name: Compilar Imagem do Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make mrproper
          make defconfig
          ./scripts/config --disable CONFIG_ACPI
          ./scripts/config --disable CONFIG_FTRACE
          ./scripts/config --disable CONFIG_FUNCTION_TRACER
          make -j2 KCFLAGS="-Wno-error -fpermissive -w"
