name: Compilar RIO NovaKernel M52
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o Codigo-Fonte
        uses: actions/checkout@v4

      - name: Instalar Ferramentas Oficiais e Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential flex git libssl-dev libcrypto++-dev libelf-dev ccache lz4 liblz4-tool clang lld llvm

      - name: Compilar Imagem do Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          make clean
          make mrproper
          make m52xq_defconfig
          make -j$(nproc) CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-

      - name: Salvar Arquivo Boot final
        uses: actions/upload-artifact@v4
        with:
          name: RIO_Kernel_M52
          path: arch/arm64/boot/Image
